# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f80c5a5760ed28ed52f46d342a579abb5f3ccbd70b141a439365eb6db3e8471535acbc3de5df301a9daa9f1ed4d9b3c5483e582c2d4802844ec52962a1f84a8

test:
  secret_key_base: f9d337386b78537315df4de19afcd548fe06a633a76eab426ead54fafe858ad2a24a69db797009724481efc9466922015cbd79830cdf0efb53281dda25602c35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
