# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93ebe0ee7e9aba7e9c2484847b63cca4e7d8dc9154518a03e23da7cc222a44d3dbebcbfdee1018a5e36eef7f85641af78aa0b7ce534efb4d2c27e21a5beb42bb

test:
  secret_key_base: 5c8139f41fc8a5eb5c0ba6e7e0349deb7fa251b071cebe4d3ad466e4ca9c5e7583212af4f5e37c4ba8e7c4d6b4b1aaecb7f0b8325a0a79396465c625b88e9f45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
