# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93168c8de4dece5757c36ab8111edf85ae09a561a2b888b9436c041cdc2b1505fd059636e546e695649c313c295ccab9f8fcc19c81cc7a8d38c5590bfd4ec0f3

test:
  secret_key_base: a3c85e96249b0f42d93848e43cfca010ee9b9e28b46f59b9932c6bc9487bc884ffb6f33a723c8fa171ba03ce3b7d9d6c1d4cb25de6936b8620623564d6200209

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
