# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4474e478f267b8c258554f6a58b7a2692a434559a0b67833de2b4f6276bf2c5f8e5e97cf6d9bdf24162cb252a3d2bbefc0e1ea342645fd3cee44b26b5036e6a

test:
  secret_key_base: 20eb05dae708798639fd558e43165e69dca35a08129294de3e3a0cd12e2ad47f72f9d2e435a0293b88edcf086a496195c1d8e77e44f832be100f2f2fc0d0d8d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
