# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1cefe3a27b277ea380a52ce9a44b828de2a2601c3e6b0b9312912c804887268bcffc166a7092280e001a30ec8315a250108a43c28bae9fcbeeb46114a75768e

test:
  secret_key_base: e9e82bf0a598c1cedb97314fd39b2185510a74f78320be78545175834b0abcb0c9ee8761878d28596cc73b7d4951cd6a4f5bd1e33acd13b4075cc87f2255a8e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
