# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a368db19f450084c19638dfc070557e058f6ef9e5d15cc37695974ee963e306d4ccba13d3cb22b015ddf77684cf4e1d074c4d80f6935f882516854bfec25eff1

test:
  secret_key_base: 5df3c12131a7aba47ab1d7149d820d353f2f9511c500901e3fdfb787981b05054955bb5b6752e03368a6d6a67d070cf3d1ff09f1dedfe4fd57b7f24834653e5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
